### ISSUE TITLE
Unable to get request object in the verifier function.

### ISSUE THREAD

**Issue by sonallakhera** [Mawi137/passport-firebase-jwt#11]
`const firebaseStrategy = new FirebaseStrategy(
    {
        jwtFromRequest: FirebaseExtractJWT.fromAuthHeaderAsBearerToken(),
        passReqToCallback: true
    },
    (...args) => { console.log(args); }
    // firebaseVerifier
);`

the arguments will always be [jwt_token, next] but not as specified in the lib function as [request, jwt_token, next]

**Comment by Mawi137** [comment]
Hi, should be fixed in version `1.2.0`
