### ISSUE TITLE
Add a TypeScript declaration file

### ISSUE THREAD

**Issue by oznecniV97** [Mawi137/passport-firebase-jwt#5]
In command `import { ExtractJwt, Strategy } from 'passport-firebase-jwt';` VS Code tell me "Could not find a declaration file for module 'passport-firebase-jwt'. 'f:/prj/templates/nestjs-template/node_modules/passport-firebase-jwt/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/passport-firebase-jwt` if it exists or add a new declaration (.d.ts) file containing `declare module 'passport-firebase-jwt';`ts(7016)".

It would be great if the project is typescript compatible.

**Comment by bryan-vh** [comment]
@oznecniV97 I am trying to add this in the pull request I just made #9. Please feel free to look it over and just waiting on @Mawi137 to approve it for merging.

**Comment by Mawi137** [comment]
Hi sorry for taking so long. I just published version 1.1.0. Let me know if it works as expected!

**Comment by jayantwalvekar** [comment]
@Mawi137 @bryan-vh I am using 1.1.0. However, VSCode still gives the same error that @oznecniV97 faced. As I am new to JS/TS, any pointers/workaround to get it working would be great help!

**Comment by TrejGun** [comment]
https://github.com/Mawi137/passport-firebase-jwt/pull/10

**Comment by Mawi137** [comment]
Merged and released under version 1.1.1!
